#define SECRET_SSID "Linksys00441"
#define SECRET_PASS "ikd0fyaguz"
#define MQTT_SERVER "192.168.1.127"
#define MQTT_PASS "admin"
#define MQTT_USER "admin"
#define MQTT_TOPIC "1/temperatur/stue/1"
#define FAN_TOPIC "1/fan/stue/1"